# ðŸ“› Nom du workflow
name: Build and Deploy Calculateur Carbo

# ðŸš€ Ce workflow se dÃ©clenche Ã  chaque push sur main
on:
  push:
    branches:
      - master

# âš™ï¸ Jobs Ã  exÃ©cuter
jobs:
  build:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest  # Machine virtuelle Linux

    steps:
      # ðŸ§¾ Ã‰tape 1 â€“ RÃ©cupÃ¨re le code de ton repo
      - name: Checkout code
        uses: actions/checkout@v3

      # ðŸ³ Ã‰tape 2 â€“ Build de l'image Docker qui sert le site
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/carbo:latest .

      # ðŸ” Ã‰tape 3 â€“ Login Docker Hub (avec secrets GitHub)
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # ðŸ“¦ Ã‰tape 4 â€“ Push de l'image
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/carbo:latest

      # ðŸ“¦ Ã‰tape 5 â€“ Mise a jour de l'image en prod
      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATEKEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan gcourtot.fr >> ~/.ssh/known_hosts
        shell: bash

      - name: Deploy via SSH
        run: |
          ssh -i ~/.ssh/id_ed25519 nem0oo@gcourtot.fr './srv/carbo/update-carbo.sh'